name       : xorg-driver-video-amdgpu
version    : 1.0.0
release    : 1
source     :
    - http://xorg.freedesktop.org/releases/individual/driver/xf86-video-amdgpu-1.0.0.tar.gz : 686fa7b68db91468ee33ea2f84e16ed23c6aa89ded0c984b5a3425a80b777581
license    : MIT
summary    : Support for AMDGPU devices
description: |
    Support for AMDGPU devices
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libdrm_amdgpu)
    - pkgconfig(gbm)
    - pkgconfig(xextproto)
    - pkgconfig(libudev)
    - pkgconfig(gl)
    - pkgconfig(xorg-server)
    - pkgconfig(fontsproto)
    - pkgconfig(xf86driproto)
setup      : |
    export CFLAGS="${CFLAGS/-Wl,-z,now/}"
    export LDFLAGS="${LDFLAGS/-Wl,-z,now/}"
    %configure --disable-static
build      : |
    export CFLAGS="${CFLAGS/-Wl,-z,now/}"
    export LDFLAGS="${LDFLAGS/-Wl,-z,now/}"
    %make
install    : |
    export CFLAGS="${CFLAGS/-Wl,-z,now/}"
    export LDFLAGS="${LDFLAGS/-Wl,-z,now/}"
    %make_install
