name       : xorg-driver-video-amdgpu
version    : 19.1.0
release    : 24
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-amdgpu-19.1.0.tar.bz2 : 4f0ea4e0ae61995ac2b7c72433d31deab63b60c78763020aaa1b28696124fe5d
license    : MIT
summary    : Support for AMDGPU devices
component  : xorg.driver
description: |
    Support for AMDGPU devices
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(gbm)
    - pkgconfig(libudev)
    - pkgconfig(xorg-server)
optimize   :
    - no-bind-now
    - no-symbolic
setup      : |
    %configure --disable-static \
               --with-xorg-conf-dir=/usr/share/X11/xorg.conf.d
build      : |
    %make
install    : |
    %make_install
