name       : xorg-driver-video-amdgpu
version    : 21.0.0
release    : 27
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-amdgpu-21.0.0.tar.gz : c3df02cc280c120d07eac01559b1e2c09890546f5044d4853209e5eff71a2f7e
license    : MIT
summary    : Support for AMDGPU devices
component  : xorg.driver
description: |
    Support for AMDGPU devices
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(gbm)
    - pkgconfig(libudev)
    - pkgconfig(xorg-server)
    - pkgconfig(xproto)
optimize   :
    - no-bind-now
    - no-symbolic
setup      : |
    %configure --disable-static \
               --with-xorg-conf-dir=/usr/share/X11/xorg.conf.d
build      : |
    %make
install    : |
    %make_install
