name       : xorg-driver-video-amdgpu
version    : 19.0.1
release    : 23
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-amdgpu-19.0.1.tar.gz : 1ad8d92a47453360fdaf07c80ac03e7bb8c1548f0cec4c2aa0166aa9ddd26dff
license    : MIT
summary    : Support for AMDGPU devices
component  : xorg.driver
description: |
    Support for AMDGPU devices
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(gbm)
    - pkgconfig(libudev)
    - pkgconfig(xorg-server)
optimize   :
    - no-bind-now
    - no-symbolic
setup      : |
    %configure --disable-static \
               --with-xorg-conf-dir=/usr/share/X11/xorg.conf.d
build      : |
    %make
install    : |
    %make_install
