name       : xorg-driver-video-amdgpu
version    : 19.0.0
release    : 22
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-amdgpu-19.0.0.tar.bz2 : 8836147d4755908ec9e192b7cc485fbc2ce7706de33f7bea515294d3ba4c4f51
license    : MIT
summary    : Support for AMDGPU devices
component  : xorg.driver
description: |
    Support for AMDGPU devices
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(gbm)
    - pkgconfig(libudev)
    - pkgconfig(xorg-server)
optimize   :
    - no-bind-now
    - no-symbolic
setup      : |
    %configure --disable-static \
               --with-xorg-conf-dir=/usr/share/X11/xorg.conf.d
build      : |
    %make
install    : |
    %make_install
