name       : xorg-driver-video-amdgpu
version    : 1.1.1
release    : 5
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-amdgpu-1.1.1.tar.gz : 40dec655b7f9385d08fd648c359eff63012bfacc16397590ad2f9682e1e4527c
license    : MIT
summary    : Support for AMDGPU devices
component  : xorg.driver
description: |
    Support for AMDGPU devices
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libdrm_amdgpu)
    - pkgconfig(gbm)
    - pkgconfig(xextproto)
    - pkgconfig(libudev)
    - pkgconfig(gl)
    - pkgconfig(xorg-server)
    - pkgconfig(fontsproto)
    - pkgconfig(xf86driproto)
optimize   : no-bind-now
setup      : |
    %configure --disable-static --with-xorg-conf-dir=/usr/share/X11/xorg.conf.d
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 conf/10-amdgpu.conf $installdir/usr/share/X11/xorg.conf.d/10-amdgpu.conf
