name       : xorg-driver-video-amdgpu
version    : 1.0.1
release    : 2
source     :
    - http://xorg.freedesktop.org/releases/individual/driver/xf86-video-amdgpu-1.0.1.tar.gz : 4fa97f7647af69d2195c78bf51aebaed5149f9e4a9b78690828cb08186dd91b2
license    : MIT
summary    : Support for AMDGPU devices
description: |
    Support for AMDGPU devices
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libdrm_amdgpu)
    - pkgconfig(gbm)
    - pkgconfig(xextproto)
    - pkgconfig(libudev)
    - pkgconfig(gl)
    - pkgconfig(xorg-server)
    - pkgconfig(fontsproto)
    - pkgconfig(xf86driproto)
setup      : |
    export CFLAGS="${CFLAGS/-Wl,-z,now/}"
    export LDFLAGS="${LDFLAGS/-Wl,-z,now/}"
    %configure --disable-static
build      : |
    export CFLAGS="${CFLAGS/-Wl,-z,now/}"
    export LDFLAGS="${LDFLAGS/-Wl,-z,now/}"
    %make
install    : |
    export CFLAGS="${CFLAGS/-Wl,-z,now/}"
    export LDFLAGS="${LDFLAGS/-Wl,-z,now/}"
    %make_install
