name       : xorg-driver-video-amdgpu
version    : 1.2.0
release    : 7
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-amdgpu-1.2.0.tar.gz : 99c572cda61007e6da7740a2eb5eb46ea882cc9a51db2c14bb07ba92660deb7a
license    : MIT
summary    : Support for AMDGPU devices
component  : xorg.driver
description: |
    Support for AMDGPU devices
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libdrm_amdgpu)
    - pkgconfig(gbm)
    - pkgconfig(xextproto)
    - pkgconfig(libudev)
    - pkgconfig(gl)
    - pkgconfig(xorg-server)
    - pkgconfig(fontsproto)
    - pkgconfig(xf86driproto)
optimize   : no-bind-now
setup      : |
    %configure --disable-static --with-xorg-conf-dir=/usr/share/X11/xorg.conf.d
build      : |
    %make
install    : |
    %make_install
