name       : xorg-driver-video-amdgpu
version    : 1.4.0
release    : 14
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-amdgpu-1.4.0.tar.gz : 61458988659f662e7973c8ce6a9158bbd2c9edd82c92eae8fa068245d9ddc482
license    : MIT
summary    : Support for AMDGPU devices
component  : xorg.driver
description: |
    Support for AMDGPU devices
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libdrm_amdgpu)
    - pkgconfig(gbm)
    - pkgconfig(xextproto)
    - pkgconfig(libudev)
    - pkgconfig(gl)
    - pkgconfig(xorg-server)
    - pkgconfig(fontsproto)
    - pkgconfig(xf86driproto)
optimize   : no-bind-now
setup      : |
    %configure --disable-static --with-xorg-conf-dir=/usr/share/X11/xorg.conf.d
build      : |
    %make
install    : |
    %make_install
