name       : xorg-driver-video-amdgpu
version    : 1.1.0
release    : 3
source     :
    - http://xorg.freedesktop.org/releases/individual/driver/xf86-video-amdgpu-1.1.0.tar.gz : d3ee9e25e9bbeade7077ebf64600a288d9511fcd8c454dedce3404b3fbd94f29
license    : MIT
summary    : Support for AMDGPU devices
component  : xorg.driver
description: |
    Support for AMDGPU devices
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libdrm_amdgpu)
    - pkgconfig(gbm)
    - pkgconfig(xextproto)
    - pkgconfig(libudev)
    - pkgconfig(gl)
    - pkgconfig(xorg-server)
    - pkgconfig(fontsproto)
    - pkgconfig(xf86driproto)
optimize   : no-bind-now
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
